<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>Logic_Layer</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Data Layer\Data Layer.csproj" />
    <ProjectReference Include="..\Entity Layer\Entity Layer.csproj" />
  </ItemGroup>

</Project>
